In [11]:
import numpy as np
x = [14,16,6,10,8,15,15,8,8,15]
y = [5,5,0,1,2,6,7,2,1,4]
print(x)
print(y)

[14, 16, 6, 10, 8, 15, 15, 8, 8, 15]
[5, 5, 0, 1, 2, 6, 7, 2, 1, 4]


In [12]:
xx = 0
yy = 0
for i in x:
    xx = xx+i;
for i in y:
    yy = yy+i;
    
print(xx,yy)

115 33


In [13]:
xx = xx/len(x)
yy = yy/len(y)
print(xx,yy)

11.5 3.3


In [14]:
a=[]
b=[]
for i in x:
    a.append(i-xx)
for i in y:
    b.append(i-yy)
print(a)
print(b)

[2.5, 4.5, -5.5, -1.5, -3.5, 3.5, 3.5, -3.5, -3.5, 3.5]
[1.7000000000000002, 1.7000000000000002, -3.3, -2.3, -1.2999999999999998, 2.7, 3.7, -1.2999999999999998, -2.3, 0.7000000000000002]


In [15]:
mat = np.stack((a,b))
print(mat)

[[ 2.5  4.5 -5.5 -1.5 -3.5  3.5  3.5 -3.5 -3.5  3.5]
 [ 1.7  1.7 -3.3 -2.3 -1.3  2.7  3.7 -1.3 -2.3  0.7]]


In [16]:
tmat = np.column_stack((a,b))
print(tmat)

[[ 2.5  1.7]
 [ 4.5  1.7]
 [-5.5 -3.3]
 [-1.5 -2.3]
 [-3.5 -1.3]
 [ 3.5  2.7]
 [ 3.5  3.7]
 [-3.5 -1.3]
 [-3.5 -2.3]
 [ 3.5  0.7]]


In [17]:
fmat = [[sum(i*j for i,j in zip(mat_row,tmat_col)) for tmat_col in zip(*tmat)] for mat_row in mat]
print(fmat)

[[132.5, 75.5], [75.5, 52.099999999999994]]


In [18]:
fmat  = np.array(fmat)
fmat=fmat/10
print(fmat)

[[13.25  7.55]
 [ 7.55  5.21]]


In [19]:
e,v = np.linalg.eigh(fmat)
print(e)
print(v)

[ 0.67646857 17.78353143]
[[ 0.51479058 -0.85731596]
 [-0.85731596 -0.51479058]]


In [20]:
print(v[0])
print(v[1])

[ 0.51479058 -0.85731596]
[-0.85731596 -0.51479058]


In [21]:
pc1= [];
pc2= [];
for i in range(len(tmat)):
    pc1.append(np.dot(tmat[i],v[1]))
    pc2.append(np.dot(tmat[i],v[0]))


In [22]:
print(pc1)
print(pc2)


[-3.0184338907551638, -4.733065816665585, 6.414046705142807, 2.4699922748707075, 3.6698336223298718, -4.3905404321616315, -4.905331010612889, 3.6698336223298718, 4.184624200781129, -3.3609592752591175]
[-0.17046069089571514, 0.8591204660067993, -0.0022055037297197266, 1.1996408471200986, -0.6872562727376266, -0.5129860753996685, -1.3703020383548794, -0.6872562727376266, 0.17005969021758416, 1.2016458505107526]
