In [9]:
import numpy as np

In [10]:
x=[14,16,6,10,8,15,15,8,8,15]
y=[5,5,0,1,2,6,7,2,1,4]
print(x,y)

[14, 16, 6, 10, 8, 15, 15, 8, 8, 15] [5, 5, 0, 1, 2, 6, 7, 2, 1, 4]


In [11]:
xbar=sum(x)/(len(x))
print(xbar)

11.5


In [12]:
ybar=sum(y)/(len(y))
print(ybar)

3.3


In [13]:
arr=[]
for i in range(len(x)):
    arr.append(x[i]-xbar)
print(arr)

[2.5, 4.5, -5.5, -1.5, -3.5, 3.5, 3.5, -3.5, -3.5, 3.5]


In [14]:
arr1=[]
for i in range(len(y)):
    arr1.append(y[i]-ybar)
print(arr1)

[1.7000000000000002, 1.7000000000000002, -3.3, -2.3, -1.2999999999999998, 2.7, 3.7, -1.2999999999999998, -2.3, 0.7000000000000002]


In [18]:
x1=np.square(arr)
print(x1)
cov_x=sum(x1)/(len(x)-1)
print(cov_x)


[ 6.25 20.25 30.25  2.25 12.25 12.25 12.25 12.25 12.25 12.25]
14.722222222222221


In [21]:
y1=np.square(arr1)
print(y1)
cov_y=sum(y1)/(len(x)-1)
print(cov_y)

[ 2.89  2.89 10.89  5.29  1.69  7.29 13.69  1.69  5.29  0.49]
5.788888888888888


In [22]:
xy=np.multiply(arr,arr1)
print(xy)
cov_xy=sum(xy)/(len(x)-1)
print(cov_xy)

[ 4.25  7.65 18.15  3.45  4.55  9.45 12.95  4.55  8.05  2.45]
8.38888888888889


In [30]:
cov_M=[[cov_x,cov_xy],
    [cov_xy,cov_y]]
print(cov_M)
e,v=np.linalg.eigh(cov_M)
print(e,v)

[[14.722222222222221, 8.38888888888889], [8.38888888888889, 5.788888888888888]]
[ 0.75163174 19.75947937] [[ 0.51479058 -0.85731596]
 [-0.85731596 -0.51479058]]
