In [1]:
import numpy as np
from sklearn.model_selection import train_test_split             
from sklearn import datasets
from collections import Counter

In [2]:
iris = datasets.load_iris() 
X = iris.data
y = iris.target
names = iris.target_names

In [3]:
print(X[:10])
print(y[:30])
print(names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
['setosa' 'versicolor' 'virginica']


In [4]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.4)

In [5]:
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))
#print(x_test[:10])

90
60
90
60


In [6]:
def euclidean(x, x2):
    sum=0
    for ix,ix2 in zip(x,x2):
        sum+=(ix-ix2)**2
    return np.sqrt(sum)

In [7]:
#euclidean([0,0], [3,4])

In [8]:
xt=[1.5,5.2,3.3,0.0]

In [9]:
dist={}
for i, x in enumerate(x_train):
    ed=euclidean(x, xt)
    dist[i]=ed


In [10]:
print(dist)

{0: 4.54972526643093, 1: 5.445181356024793, 2: 5.371219600798314, 3: 5.860887304837042, 4: 4.536518488885503, 5: 4.05585995813465, 6: 4.313930922024598, 7: 5.397221507405454, 8: 4.814561246884289, 9: 4.4777226354476225, 10: 6.019966777316965, 11: 5.06655701635736, 12: 4.127953488110059, 13: 4.421538193886828, 14: 5.406477596365308, 15: 6.136774397026503, 16: 4.068169121361598, 17: 5.9715994507334464, 18: 5.510898293381942, 19: 6.178187436457395, 20: 4.71805044483418, 21: 5.483611948342078, 22: 4.260281680828159, 23: 5.151698748956503, 24: 5.890670590009257, 25: 5.88387627334226, 26: 5.055689863905815, 27: 5.897457079114693, 28: 4.972926703662543, 29: 4.183300132670377, 30: 6.510760324263213, 31: 7.53657747256671, 32: 4.674398357008098, 33: 5.7740800133008205, 34: 5.544366510251645, 35: 5.046781152378217, 36: 6.109828148156051, 37: 6.857113095173507, 38: 5.07247474118896, 39: 6.1692787260748725, 40: 4.474371464239419, 41: 5.927900134111573, 42: 5.5830099408831435, 43: 5.930430001273095,

In [11]:
sorted_d = sorted(dist.items(), key=lambda kv: kv[1])

In [12]:
print(sorted_d)

[(73, 4.016217125604641), (5, 4.05585995813465), (16, 4.068169121361598), (12, 4.127953488110059), (71, 4.158124577258358), (29, 4.183300132670377), (72, 4.2118879377305385), (22, 4.260281680828159), (86, 4.272001872658765), (51, 4.27551166528639), (62, 4.296510211788167), (6, 4.313930922024598), (68, 4.332435804486894), (61, 4.38520238985614), (70, 4.387482193696061), (74, 4.407947368106838), (57, 4.415880433163923), (84, 4.4170125650715555), (13, 4.421538193886828), (45, 4.4294469180700204), (66, 4.456455991031438), (63, 4.468780594300865), (40, 4.474371464239419), (9, 4.4777226354476225), (4, 4.536518488885503), (60, 4.544227107000705), (0, 4.54972526643093), (54, 4.636809247747852), (32, 4.674398357008098), (67, 4.716990566028302), (20, 4.71805044483418), (47, 4.788527957525152), (8, 4.814561246884289), (78, 4.850773134253961), (58, 4.937610758251403), (28, 4.972926703662543), (52, 5.029910535983717), (80, 5.033885179461287), (75, 5.042816673249187), (82, 5.043808085167397), (35, 5

In [13]:
k=90
neighbors=[]
for i in range(k):
    neighbors.append(sorted_d[i][0])
print(neighbors)

[73, 5, 16, 12, 71, 29, 72, 22, 86, 51, 62, 6, 68, 61, 70, 74, 57, 84, 13, 45, 66, 63, 40, 9, 4, 60, 0, 54, 32, 67, 20, 47, 8, 78, 58, 28, 52, 80, 75, 82, 35, 26, 11, 38, 23, 76, 50, 2, 7, 14, 1, 21, 18, 34, 42, 48, 81, 53, 69, 33, 3, 87, 25, 24, 27, 41, 43, 17, 10, 49, 89, 36, 15, 55, 39, 19, 88, 65, 77, 56, 30, 44, 64, 83, 85, 37, 46, 79, 59, 31]


In [14]:
classes=[ y_train[i] for i in neighbors]
print(classes)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [15]:
count=Counter(classes)
print(count)

Counter({0: 32, 1: 32, 2: 26})


In [16]:
keys= list( count.keys() )
print('keys=', keys)
values=list( count.values() )
print('values=',values)

keys= [0, 1, 2]
values= [32, 32, 26]


In [17]:
index_of_max_values=values.index(max(values)) 
print('index of max value=', index_of_max_values)
y_hat=keys[index_of_max_values]
print('predict class=',y_hat)

index of max value= 0
predict class= 0
